apps/customer/urls.py
from django.urls import path

from apps.customer import views

urlpatterns = [
    # path('create/', views., name='myurl'),
    path('all/', views.ClientViewList.as_view(), name='client_list'),
    path('create/', views.AddClient.as_view(), name='create_client'),
    path('<int:pk>/update/', views.UpdateClient.as_view(), name='update_client'),
    path('<int:pk>/delete/', views.deleteClient, name='delete_client'),
    path('<int:pk>/', views.ClientDetailView.as_view(), name='client-detail'),
    # path('client/<int:pk>/delete/', views.DeleteClient.as_view(), name='delete_client'),
]

scoringsystem/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

api_patterns = [
    # apps
    # path('', admin.site.urls),

]

template_patterns = [
    path('client/', include('apps.customer.urls')),
    path('', include('apps.loan.urls')),

]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/', include(api_patterns)),
    path('', include(template_patterns)),
    path('accounts/', include('django.contrib.auth.urls')),

    # documentation
    path("swagger/", schema_view.with_ui("swagger", cache_timeout=0), name="schema-swagger-ui", ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc-ui"),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/customer/models.py
from django.db import models
from apps.loan.models import Aggregated_info, Loan_history
from django.shortcuts import reverse

SEX_CHOICES = (
    ('F', 'Female'),
    ('M', 'Male')
)


class Client(models.Model):
    client_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=64, verbose_name='Имя')
    lastname = models.CharField(max_length=128, verbose_name='Фамилия')
    fatherstname = models.CharField(max_length=64, verbose_name='Отчество')
    dateofbirth = models.DateField(verbose_name='Дата рождения')
    sex = models.CharField(max_length=16, choices=SEX_CHOICES)
    сitizenship = models.CharField(max_length=155, verbose_name='Гражданство')
    inn = models.CharField(max_length=64, verbose_name='ИНН')
    document_number = models.CharField(max_length=64, verbose_name='Номер документа')
    expiration_date = models.DateField(verbose_name='срок действия')
    date_of_issue = models.DateField(verbose_name='дата выдачи')
    distribution_organization = models.CharField(max_length=256, verbose_name='орган выдачи')
    address = models.CharField(max_length=256, verbose_name='Адрес')
    Occupation = models.CharField(max_length=256, verbose_name='Род деятельности')
    family_status = models.CharField(max_length=256, verbose_name='Семейное положение')
    contact = models.CharField(max_length=256, verbose_name='Контакты')
    loan_history = models.ForeignKey(Loan_history, on_delete=models.CASCADE, related_name='client_lh', null=True,
                                     blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('myurl', kwargs={'id': self.client_id, 'name': self.name})

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'

apps/customer/forms.py
from django import forms

from .models import Client


class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ['name', 'lastname',
                  'fatherstname', 'dateofbirth',
                  'sex', 'сitizenship',
                  'inn', 'document_number',
                  'expiration_date', 'date_of_issue',
                  'distribution_organization', 'address',
                  'Occupation', 'family_status',
                  'contact', 'loan_history', ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        form_fields = self.fields

        for field in form_fields:
            self.fields[field].widget.attrs.update({'class': 'form-control'})

apps/customer/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DeleteView, DetailView
from django.views.generic.edit import UpdateView

from apps.loan.models import Loan_history
from .forms import ClientForm
from .models import Client


class ClientViewList(ListView):
    def get(self, request):
        clients = Client.objects.all()
        return render(request, 'pages/customer/customer-table.html', {'clients': clients})


class AddClient(CreateView):
    model = Client
    form_class = ClientForm
    template_name = 'customer/create.html'
    success_url = '/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['loan_histories'] = Loan_history.objects.all()
        return context


class ClientDetailView(DetailView):
    model = Client
    # template_name = 'customer/client_detail.html'
    context_object_name = 'client'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['loan_histories'] = Loan_history.objects.all()
        context['client_list'] = Client.objects.all()
        return context


class UpdateClient(UpdateView):
    form_class = ClientForm
    model = Client
    template_name = 'customer/update.html'

    def get_success_url(self):
        return reverse_lazy('client-detail', kwargs={'pk': self.object.pk})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['loan_histories'] = Loan_history.objects.all()
        return context


class DeleteClient(DeleteView):
    model = Client
    form_class = ClientForm
    template_name = 'customer/delete.html'
    success_url = '/'


def deleteClient(request, pk):
    client = get_object_or_404(Client, pk=pk)
    form = ClientForm(request.POST or None, instance=client)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, 'customer/delete.html', {'object': client})

templates/customer/create.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="{% static "assets/css/style.css" %}">
    <title>Личные данные</title>
</head>
<body>
<div class="card-body">
    <!-- Author: FormBold Team -->
    <!-- Learn More: https://formbold.com -->
    <div class="formbold-form-wrapper">

        <form action="{% url 'create_client' %}" method="POST">
            {% csrf_token %}
            <div class="formbold-form-title">
                <h2 class="">Личная информация</h2>
                <p></p>
            </div>

            <div class="formbold-input-flex">
                <div>
                    <label for="name" class="formbold-form-label">
                        Имя
                    </label>
                    <input
                            type="text"
                            name="name"
                            id="name"
                            class="formbold-form-input"
                    />
                </div>
                <div>
                    <label for="lastname" class="formbold-form-label"> Фамилия </label>
                    <input
                            type="text"
                            name="lastname"
                            id="lastname"
                            class="formbold-form-input"
                    />
                </div>
            </div>

            <div class="formbold-input-flex">
                <div>
                    <label for="fatherstname" class="formbold-form-label"> Отчество </label>
                    <input
                            type="text"
                            name="fatherstname"
                            id="fatherstname"
                            class="formbold-form-input"
                    />
                </div>
                <div>
                    <label for="contact" class="formbold-form-label"> Сотовый телефон </label>
                    <input
                            type="number"
                            name="contact"
                            id="contact"
                            class="formbold-form-input"
                    />
                </div>
            </div>

            <div class="formbold-input-flex">
                <div>
                    <label class="formbold-form-label"> Пол </label>
                    <select class="formbold-form-input" name="sex" required="" id="id_sex">
                        <option value="F">Женский</option>
                        <option value="M">Мужской</option>

                    </select>
                </div>
                <div>
                    <label for="dateofbirth" class="formbold-form-label"> Дата рождения </label>
                    <input
                            type="date"
                            name="dateofbirth"
                            id="dateofbirth"
                            class="formbold-form-input"
                    />
                </div>
            </div>


            <div class="formbold-mb-3">
                <label for="address" class="formbold-form-label">
                    Адрес
                </label>
                <input
                        type="text"
                        name="address"
                        id="address"
                        class="formbold-form-input"
                />
            </div>

            <div class="formbold-mb-3">
                <label for="сitizenship" class="formbold-form-label">
                    Гражданство
                </label>
                <input
                        type="text"
                        name="сitizenship"
                        id="сitizenship"
                        class="formbold-form-input"
                />
            </div>
            <br>
            <hr>
            <div class="formbold-form-title">
                <h4 class="">Паспортные данные</h4>
                <p>
                </p>
            </div>

            <div class="formbold-mb-3">
                <label for="inn" class="formbold-form-label">
                    ИНН
                </label>
                <input
                        type="text"
                        name="inn"
                        id="inn"
                        class="formbold-form-input"
                />
            </div>
            <div class="formbold-mb-3">
                <label for="distribution_organization" class="formbold-form-label">
                    Орган выдачи
                </label>
                <input
                        type="text"
                        name="distribution_organization"
                        id="distribution_organization"
                        class="formbold-form-input"
                />
            </div>
            <div class="formbold-input-flex">
                <div>
                    <label for="date_of_issue" class="formbold-form-label"> Дата выдачи </label>
                    <input
                            type="date"
                            name="date_of_issue"
                            id="date_of_issue"
                            class="formbold-form-input"
                    />
                </div>
                <div>
                    <label for="expiration_date" class="formbold-form-label"> Срок действия</label>
                    <input
                            type="date"
                            name="expiration_date"
                            id="expiration_date"
                            class="formbold-form-input"
                    />
                </div>
            </div>
            <div>
                <label for="document_number" class="formbold-form-label"> Номер документа </label>
                <input
                        type="text"
                        name="document_number"
                        id="document_number"
                        class="formbold-form-input"
                />
            </div>
            <br>
            <hr>
            <br>
            <div class="formbold-mb-3">
                <label for="Occupation" class="formbold-form-label">
                    Род деятельности
                </label>
                <input
                        type="text"
                        name="Occupation"
                        id="Occupation"
                        class="formbold-form-input"
                />
            </div>

            <div class="formbold-mb-3">
                <label for="family_status" class="formbold-form-label">
                    Семейное положение
                </label>
                <input
                        type="text"
                        name="family_status"
                        id="family_status"
                        class="formbold-form-input"
                />
            </div>
            <div class="formbold-mb-3">
                <div>
                    <label class="formbold-form-label">Кредитная история</label>
                    <select class="formbold-form-input" name="loan_history">
                        <option value="">Не выбрано</option>
                        {% for loan_history in loan_histories %}
                            <option value="{{ loan_history.loanhistory_id }}">{{ loan_history.agg_info }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>

            <button type='submit' class="formbold-btn">Сохранить</button>
        </form>
    </div>
</div>
<style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');

    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
    }

    body {
        font-family: 'Inter', sans-serif;
    }

    .formbold-mb-3 {
        margin-bottom: 15px;
    }

    .formbold-relative {
        position: relative;
    }

    .formbold-opacity-0 {
        opacity: 0;
    }

    .formbold-stroke-current {
        stroke: currentColor;
    }

    #supportCheckbox:checked ~ div span {
        opacity: 1;
    }

    .formbold-main-wrapper {
        display: flex;
        align-items: center;
        justify-content: center;
        padding: 48px;
    }

    .formbold-form-wrapper {
        margin: 0 auto;
        max-width: 570px;
        width: 100%;
        background: white;
        padding: 40px;
    }

    .formbold-img {
        margin-bottom: 45px;
    }

    .formbold-form-title {
        margin-bottom: 30px;
    }

    .formbold-form-title h2 {
        font-weight: 600;
        font-size: 28px;
        line-height: 34px;
        color: #07074d;
    }

    .formbold-form-title h4 {
        font-weight: 600;
        font-size: 20px;
        line-height: 34px;
        color: #07074d;
    }

    .formbold-form-title p {
        font-size: 16px;
        line-height: 24px;
        color: #536387;
        margin-top: 12px;
    }

    .formbold-input-flex {
        display: flex;
        gap: 20px;
        margin-bottom: 15px;
    }

    .formbold-input-flex > div {
        width: 50%;
    }

    .formbold-form-input {
        text-align: center;
        width: 100%;
        padding: 13px 22px;
        border-radius: 5px;
        border: 1px solid #dde3ec;
        background: #ffffff;
        font-weight: 500;
        font-size: 16px;
        color: #536387;
        outline: none;
        resize: none;
    }

    .formbold-form-input:focus {
        border-color: #6a64f1;
        box-shadow: 0px 3px 8px rgba(0, 0, 0, 0.05);
    }

    .formbold-form-label {
        color: #536387;
        font-size: 14px;
        line-height: 24px;
        display: block;
        margin-bottom: 10px;
    }

    .formbold-checkbox-label {
        display: flex;
        cursor: pointer;
        user-select: none;
        font-size: 16px;
        line-height: 24px;
        color: #536387;
    }

    .formbold-checkbox-label a {
        margin-left: 5px;
        color: #6a64f1;
    }

    .formbold-input-checkbox {
        position: absolute;
        width: 1px;
        height: 1px;
        padding: 0;
        margin: -1px;
        overflow: hidden;
        clip: rect(0, 0, 0, 0);
        white-space: nowrap;
        border-width: 0;
    }

    .formbold-checkbox-inner {
        display: flex;
        align-items: center;
        justify-content: center;
        width: 20px;
        height: 20px;
        margin-right: 16px;
        margin-top: 2px;
        border: 0.7px solid #dde3ec;
        border-radius: 3px;
    }

    .formbold-btn {
        font-size: 16px;
        border-radius: 5px;
        padding: 14px 25px;
        border: none;
        font-weight: 500;
        background-color: #6a64f1;
        color: white;
        cursor: pointer;
        margin-top: 25px;
    }

    .formbold-btn:hover {
        box-shadow: 0px 3px 8px rgba(0, 0, 0, 0.05);
    }
</style>
</body>
</html>

templates/customer/delete.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="{% static "assets/css/style.css" %}">
    <title>Личные данные</title>
</head>
{% block content %}
    <body>
    <div class="card-body">
        <!-- Author: FormBold Team -->
        <!-- Learn More: https://formbold.com -->
        <div class="formbold-form-wrapper">
            {#            <form method="POST">#}
            {#                {% csrf_token %}#}
            {#                <div class="formbold-form-title">#}
            {#                    <h2 class="">Удаление</h2>#}
            {#                </div>#}
            {##}
            {#                <div class="formbold-input-flex">#}
            {#                    <div>#}
            {#                        <label for="id_name" class="formbold-form-label">Вы действительно хотите#}
            {#                            удалить {{ object }} ? </label>#}
            {#                    </div>#}
            {#                </div>#}
            {#                <input type='submit' value="Удалить" class="formbold-btn">#}
            {#            </form>#}
            <form method="post">
                {% csrf_token %}
                <label class="formbold-form-label">Вы действительно хотите удалить {{ object }} ? </label>
                <input type="submit" value="Confirm">
            </form>
        </div>
    </div>
{% endblock %}
<style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');

    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
    }

    body {
        font-family: 'Inter', sans-serif;
    }

    .formbold-mb-3 {
        margin-bottom: 15px;
    }

    .formbold-relative {
        position: relative;
    }

    .formbold-opacity-0 {
        opacity: 0;
    }

    .formbold-stroke-current {
        stroke: currentColor;
    }

    #supportCheckbox:checked ~ div span {
        opacity: 1;
    }

    .formbold-main-wrapper {
        display: flex;
        align-items: center;
        justify-content: center;
        padding: 48px;
    }

    .formbold-form-wrapper {
        margin: 0 auto;
        max-width: 570px;
        width: 100%;
        background: white;
        padding: 40px;
    }

    .formbold-img {
        margin-bottom: 45px;
    }

    .formbold-form-title {
        margin-bottom: 30px;
    }

    .formbold-form-title h2 {
        font-weight: 600;
        font-size: 28px;
        line-height: 34px;
        color: #07074d;
    }

    .formbold-form-title h4 {
        font-weight: 600;
        font-size: 20px;
        line-height: 34px;
        color: #07074d;
    }

    .formbold-form-title p {
        font-size: 16px;
        line-height: 24px;
        color: #536387;
        margin-top: 12px;
    }

    .formbold-input-flex {
        display: flex;
        gap: 20px;
        margin-bottom: 15px;
    }

    .formbold-input-flex > div {
        width: 50%;
    }

    .formbold-form-input {
        text-align: center;
        width: 100%;
        padding: 13px 22px;
        border-radius: 5px;
        border: 1px solid #dde3ec;
        background: #ffffff;
        font-weight: 500;
        font-size: 16px;
        color: #536387;
        outline: none;
        resize: none;
    }

    .formbold-form-input:focus {
        border-color: #6a64f1;
        box-shadow: 0px 3px 8px rgba(0, 0, 0, 0.05);
    }

    .formbold-form-label {
        color: #536387;
        font-size: 14px;
        line-height: 24px;
        display: block;
        margin-bottom: 10px;
    }

    .formbold-checkbox-label {
        display: flex;
        cursor: pointer;
        user-select: none;
        font-size: 16px;
        line-height: 24px;
        color: #536387;
    }

    .formbold-checkbox-label a {
        margin-left: 5px;
        color: #6a64f1;
    }

    .formbold-input-checkbox {
        position: absolute;
        width: 1px;
        height: 1px;
        padding: 0;
        margin: -1px;
        overflow: hidden;
        clip: rect(0, 0, 0, 0);
        white-space: nowrap;
        border-width: 0;
    }

    .formbold-checkbox-inner {
        display: flex;
        align-items: center;
        justify-content: center;
        width: 20px;
        height: 20px;
        margin-right: 16px;
        margin-top: 2px;
        border: 0.7px solid #dde3ec;
        border-radius: 3px;
    }

    .formbold-btn {
        font-size: 16px;
        border-radius: 5px;
        padding: 14px 25px;
        border: none;
        font-weight: 500;
        background-color: #6a64f1;
        color: white;
        cursor: pointer;
        margin-top: 25px;
    }

    .formbold-btn:hover {
        box-shadow: 0px 3px 8px rgba(0, 0, 0, 0.05);
    }
</style>
</body>
</html>